# Generated by Django 3.0 on 2020-07-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20200717_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
