# Generated by Django 3.0 on 2020-07-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20200717_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.Question'),
        ),
    ]
