# Generated by Django 3.0 on 2020-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_testcase_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
