# Generated by Django 3.0 on 2020-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20200718_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
