# Generated by Django 3.0 on 2020-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_language_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
