# Generated by Django 3.0 on 2020-07-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20200719_0027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionlanguagedefault',
            unique_together={('question', 'language')},
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(blank=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.Language')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.Question')),
            ],
        ),
    ]
