# Generated by Django 3.0.8 on 2020-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20200722_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='timeout',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
