# Generated by Django 3.0.8 on 2020-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_testcase_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=1000)),
            ],
        ),
    ]
