# Generated by Django 3.0.8 on 2020-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_judgeapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeapikey',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
