# Generated by Django 3.0.8 on 2020-08-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_auto_20200731_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeapikey',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
