# Generated by Django 3.2.7 on 2021-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20200903_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code_draft',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='passed_cases',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tinput',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='toutput',
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='details',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
