# Generated by Django 3.2.7 on 2021-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_auto_20211006_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tinput',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='toutput',
            field=models.TextField(blank=True),
        ),
    ]
